name: base
dependencies:
  - numpy
  - matplotlib
  - python
  - numba
  - matplotlib
  - tqdm
  - scipy
  - scikit-image
  - sphinx_rtd_theme
  - pip:
    - scikit-fmm
    - sphinx-argparse
    - hilbertcurve
    - mahotas
